steps:
  # Install dependencies
  - name: 'node:22'
    dir: 'final-todo-app-api'
    entrypoint: npm
    args: ['ci']

  # Create .env file
  - name: 'node:22'
    dir: 'todo-app'
    entrypoint: 'npm'
    args: ['run', 'create-env', '.env']
    secretEnv: ['API_KEY']
    env:
      - 'NEXT_PUBLIC_API_KEY=$$API_KEY'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--no-promote']
    dir: 'final-todo-app-api'

# Access secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/ml-training-sandbox-1/secrets/API_KEY/versions/latest
      env: 'API_KEY'

timeout: '1600s' 

options:
  logging: CLOUD_LOGGING_ONLY
